const allCliList=[
  'show aaa domain word',
  'show aaa methodlist',
  'show accesscontrol packet statistics',
  'show accessgroup',
  'show accesslists num',
  'show accesslists summary',
  'show accesslists word',
  'show accesslists',
  'show accesssharemonitor feature rule all',
  'show accesssharemonitor feature upgrade history',
  'show accesssharemonitor statistics',
  'show acconfig client',
  'show acl capability more',
  'show acl capability',
  'show acl capacity',
  'show acl res',
  'show addressbind uplink',
  'show addressbind',
  'show addressmanage',
  'show aggregateport capacity',
  'show aggregateport loadbalance',
  'show aggregateport summary inset',
  'show aggregateport summary',
  'show antiarpspoofing',
  'show apconfig summary',
  'show arp counter',
  'show arp detail ip',
  'show arp detail vxlan',
  'show arp detail',
  'show arp ip',
  'show arp oob',
  'show arp static',
  'show arp timeout',
  'show arp vrf word',
  'show arp',
  'show bfd neighbors client static',
  'show bfd neighbors details bak',
  'show bfd neighbors details format intf',
  'show bfd neighbors details pl3',
  'show bfd neighbors details',
  'show bfd neighbors ipv4 ip details',
  'show bfd neighbors ipv6 ipv6 details',
  'show bfd neighbors parmconsult',
  'show bfd neighbors vrf word details',
  'show bfd neighbors vrf word',
  'show bfd neighbors',
  'show bgp all neighbors ip hamode adjin',
  'show bgp all neighbors ip',
  'show bgp all neighbors ipv6',
  'show bgp all neighbors',
  'show bgp all summary',
  'show bgp all updategroup ip',
  'show bgp all updategroup num hamod adjout',
  'show bgp all updategroup num',
  'show bgp all updategroup',
  'show bgp all',
  'show bgp bmp neighbor',
  'show bgp bmp summary',
  'show bgp cidronly',
  'show bgp egressengineering',
  'show bgp gr status',
  'show bgp ipv4 flowspec neighbors',
  'show bgp ipv4 flowspec',
  'show bgp ipv4 srpolicy detail word',
  'show bgp ipv4 srpolicy',
  'show bgp ipv4 unicast vrf word ipmask',
  'show bgp ipv4 unicast vrf word summary',
  'show bgp ipv6 srpolicy detail word',
  'show bgp ipv6 srpolicy',
  'show bgp ipv6 unicast all summary',
  'show bgp ipv6 unicast ipv6mask',
  'show bgp ipv6 unicast summary',
  'show bgp ipv6 unicast vrf word ipv6mask',
  'show bgp ipv6 unicast vrf word summary',
  'show bgp ipv6 unicast',
  'show bgp l2vpn evpn all ipprefix detail',
  'show bgp l2vpn evpn all ipprefix ip detail',
  'show bgp l2vpn evpn all ipprefix ipv6 detail',
  'show bgp l2vpn evpn all macip',
  'show bgp l2vpn evpn all summary',
  'show bgp l2vpn evpn all updategroup',
  'show bgp l2vpn evpn evi num inclusivemulticast',
  'show bgp l2vpn evpn evi num macip detail',
  'show bgp l2vpn evpn evi num macip ip detail',
  'show bgp l2vpn evpn evi num macip',
  'show bgp linkstate linkstate detail',
  'show bgp linkstate linkstate lsclient',
  'show bgp linkstate linkstate',
  'show bgp nsr status',
  'show bgp vpnv4 unicast all summary',
  'show bgp vpnv4 unicast all updategroup',
  'show bgp vpnv4 unicast all',
  'show bgp vpnv4 unicast vrf word ip',
  'show bgp vpnv6 unicast all summary',
  'show bgp vpnv6 unicast all updategroup',
  'show bgp vpnv6 unicast all',
  'show bgp vpnv6 unicast vrf word ipv6mask',
  'show bridge ability',
  'show capwap state',
  'show card voltage',
  'show classmap',
  'show clink statistic',
  'show clock',
  'show clustermonitor status',
  'show cnp counters interface dutport',
  'show cnp counters',
  'show container images',
  'show container stats word',
  'show container',
  'show cpldfpga version detail fan',
  'show cpldfpga version detail slot',
  'show cpldfpga version detail',
  'show cpu slot',
  'show cpu',
  'show cpuprotect autodefend conf',
  'show cpuprotect autodefend config detail',
  'show cpuprotect autodefend config',
  'show cpuprotect autodefend summary',
  'show cpuprotect autoportdefend summary',
  'show cpuprotect bak0601',
  'show cpuprotect device num slot num',
  'show cpuprotect device num',
  'show cpuprotect hardwarestatistics device num slot num',
  'show cpuprotect hardwarestatistics device num',
  'show cpuprotect hardwarestatistics slot num',
  'show cpuprotect planedefend all config',
  'show cpuprotect planedefend all statistics device num',
  'show cpuprotect planedefend all statistics slot num',
  'show cpuprotect slot num',
  'show cpuprotect statistics interface dutport',
  'show cpuprotect summary',
  'show cpuprotect type dot1x',
  'show cpuprotect type type',
  'show cpuprotect',
  'show crypto key mypubkey sm2',
  'show cwmp configuration',
  'show cwmp status',
  'show defend word drop',
  'show defendzone word word counters',
  'show device id',
  'show directvlan',
  'show dldp ipv6 statistic',
  'show dldp statistic',
  'show dldp',
  'show dns proxy hide qps',
  'show dns proxy hosts',
  'show dot11 mbssid',
  'show dot11 ratelimit wlan',
  'show dot1qtunnel interfaces dutport',
  'show dot1qtunnel',
  'show dot1x guardipsegment',
  'show dot1x multimab quiet user',
  'show dot1x portcontrol',
  'show dot1x privatesupplicantonly',
  'show dot1x probetimer',
  'show dot1x staticipseg',
  'show dot1x summary',
  'show dot1x user diag mac',
  'show dot1x user mac mac',
  'show dot1x',
  'show eee interface dutport',
  'show eee interfaces status',
  'show efd core',
  'show efd ef hpage meminfo',
  'show efd ef hpage poolinfo',
  'show efd ef hpage slabinfo',
  'show efd efb',
  'show efd efinterface dutport',
  'show efd efinterface num',
  'show efd ip fpm counters',
  'show efd ip fpm flows filter',
  'show efd ip fpm statistics',
  'show efd ipv6 fpm counters',
  'show efd ipv6 fpm flows filter',
  'show efd ipv6 fpm statistics',
  'show efd slot num core',
  'show efd slot num ef hpage meminfo',
  'show efd slot num ef hpage poolinfo',
  'show efd slot num ef hpage slabinfo',
  'show efd slot num efb',
  'show efd slot num efhpage poolinfo',
  'show efd slot num efinterface num',
  'show efd slot num ip fpm counters',
  'show efd slot num ip fpm flows filter',
  'show efd slot num ip fpm statistics',
  'show efd slot num ipv6 fpm counters',
  'show efd slot num ipv6 fpm flows filter',
  'show efd slot num ipv6 fpm statistics',
  'show efm event link local dutport',
  'show efm event link local',
  'show efm packet interface dutport',
  'show efm packet',
  'show efmp capacity',
  'show efmp counter',
  'show efmp fpa',
  'show efmp ring',
  'show efmp rxpnt',
  'show egressqueue trafficstatistics interface dutport',
  'show erps rapsvlan num',
  'show erps',
  'show evpn detail',
  'show expert accessgroup',
  'show fabricinterface connectivity slot num port num',
  'show fabricinterface isolate info',
  'show fabricinterface monitor plan',
  'show fabricinterface status linkhistory device num slot num',
  'show fabricinterface status linkhistory slot num',
  'show fabricinterface status linkhistory',
  'show fabricinterface status slot num port num',
  'show fabricinterface status',
  'show fan detail',
  'show fan',
  'show file systems',
  'show firewallgroup',
  'show flowspec interfacegroup',
  'show frametag tpid interfaces dutport',
  'show frametag tpid',
  'show grpc server information',
  'show grpc subscr sample',
  'show grtd configue all detail',
  'show grtd configue all',
  'show grtd status all detail',
  'show grtd status all',
  'show gvrp configuration',
  'show gvrp statistics dutport',
  'show gvrp statistics',
  'show hdf detailinfo slot num mainnode FABRIC INF childnode protocol',
  'show heap stats',
  'show hideisis route all ipv6',
  'show hostname',
  'show hosts',
  'show httpupdate info version',
  'show info analy all colon',
  'show info analy all more blank',
  'show innerprioritytrust interfaces dutport',
  'show innerprioritytrust',
  'show install detail',
  'show install',
  'show interface aggregateport num counters',
  'show interface aggregateport num',
  'show interface arpcheck list',
  'show interface brief',
  'show interface bvi num',
  'show interface counters errors up',
  'show interface counters rate up',
  'show interface counters rate',
  'show interface counters up',
  'show interface description',
  'show interface dot1qtunnel',
  'show interface dutport counters error',
  'show interface dutport counters rate',
  'show interface dutport counters summary',
  'show interface dutport counters',
  'show interface dutport remark',
  'show interface dutport transceiver alarm',
  'show interface dutport transceiver bak0901',
  'show interface dutport transceiver diagnosis',
  'show interface dutport transceiver manuinfo',
  'show interface dutport transceiver',
  'show interface dutport',
  'show interface overlayrouter num',
  'show interface overlaytunnel num',
  'show interface status errdisabled',
  'show interface status',
  'show interface switchport backup detail',
  'show interface switchport',
  'show interface virtualaccess num',
  'show interface vlan num',
  'show interface vlan',
  'show interfaces aggregateport num',
  'show interfaces counters rate nozero',
  'show interfaces counters rate up',
  'show interfaces counters rate',
  'show interfaces counters summary up',
  'show interfaces counters summary',
  'show interfaces counters up',
  'show interfaces description',
  'show interfaces dot1qtunnel',
  'show interfaces dutport counters',
  'show interfaces dutport linkstatechange statistics',
  'show interfaces dutport transceiver alarm',
  'show interfaces dutport transceiver bak0901',
  'show interfaces dutport transceiver diagnosis',
  'show interfaces dutport transceiver manuinfo',
  'show interfaces dutport transceiver',
  'show interfaces dutport troubleshooting',
  'show interfaces dutport',
  'show interfaces faultinfo',
  'show interfaces linkstatechange statistics',
  'show interfaces macaddressmapping',
  'show interfaces overlayrouter num',
  'show interfaces overlaytunnel num',
  'show interfaces remark',
  'show interfaces status',
  'show interfaces switchport backup',
  'show interfaces tunnel num',
  'show interfaces usage up',
  'show interfaces usage',
  'show interfaces vlan num',
  'show interfaces vlan',
  'show interfaces vlanmapping',
  'show internalinterface counters errors',
  'show internalinterface counters',
  'show internalinterface status',
  'show ip accessgroup',
  'show ip bgp ip ip',
  'show ip bgp ip',
  'show ip bgp ipmask',
  'show ip bgp neighbors',
  'show ip bgp summary',
  'show ip bgp updategroup',
  'show ip bgp vrf word summary',
  'show ip bgp vrf word',
  'show ip bgp',
  'show ip defense icmpflood',
  'show ip defense synflood',
  'show ip deny nullscan',
  'show ip dhcp bind',
  'show ip dhcp binding ip',
  'show ip dhcp binding',
  'show ip dhcp conflict',
  'show ip dhcp history',
  'show ip dhcp pool',
  'show ip dhcp server statistics',
  'show ip dhcp snoop binding',
  'show ip dhcp snooping binding',
  'show ip dhcp snooping packet',
  'show ip dhcp snooping',
  'show ip dhcp usergroup pool',
  'show ip dhcp usergroup summary',
  'show ip fib route vrf word',
  'show ip fib route',
  'show ip flow cache dev num slot num',
  'show ip flow cache statistic dev num slot num',
  'show ip flow cache',
  'show ip flow export',
  'show ip fpm num num flow',
  'show ip fpm statistics',
  'show ip igmp groups detail',
  'show ip igmp groups',
  'show ip igmp snooping gdatable',
  'show ip igmp snooping querier',
  'show ip igmp snooping statistics',
  'show ip igmp snooping',
  'show ip interface brief',
  'show ip interface vlan num',
  'show ip interface',
  'show ip mroute',
  'show ip nat translation',
  'show ip nat translations verbose',
  'show ip nat translations',
  'show ip ospf bgpls state',
  'show ip ospf database external advrouter ip',
  'show ip ospf database external advrouter word',
  'show ip ospf database nssaexternal advrouter ip',
  'show ip ospf hide bgpls recordnlri num ip detail',
  'show ip ospf hide bgpls recordnlri num ip',
  'show ip ospf neighbo',
  'show ip ospf neighbor',
  'show ip ospf nsr database count',
  'show ip ospf num neighbor',
  'show ip ospf route count',
  'show ip ospf segmentrouting adjacencysid',
  'show ip ospf segmentrouting ftn',
  'show ip ospf segmentrouting i',
  'show ip ospf segmentrouting il',
  'show ip ospf segmentrouting ilm',
  'show ip ospf segmentrouting mappingserver prefixsidmap',
  'show ip ospf segmentrouting prefixsid',
  'show ip ospf segmentrouting srgb',
  'show ip ospf segmentrouting srlb',
  'show ip ospf sync',
  'show ip ospf tilfa node',
  'show ip ospf',
  'show ip packet statistic total',
  'show ip pim densemode neighbor',
  'show ip pim sparsemode interface dutport detail',
  'show ip pim sparsemode interface',
  'show ip pim sparsemode neighbor',
  'show ip ref adjacency slot num',
  'show ip ref adjacency statistics',
  'show ip ref adjacency',
  'show ip ref detail',
  'show ip ref loadbalance',
  'show ip ref rou slot num',
  'show ip ref rout slot num',
  'show ip ref route detail ip',
  'show ip ref route fast',
  'show ip ref route fastreroute',
  'show ip ref route slot num',
  'show ip ref route statistics slot num',
  'show ip ref route statistics',
  'show ip ref route vrf word',
  'show ip ref route',
  'show ip rip peer',
  'show ip rip',
  'show ip rns collectionstatistics num',
  'show ip rns collectionstatistics',
  'show ip rns configuration num',
  'show ip rns configuration',
  'show ip rns operationalstate num',
  'show ip rns operationalstate',
  'show ip rns reactionconfiguration num',
  'show ip rns reactiontrigger num',
  'show ip rns statistics num',
  'show ip rns statistics',
  'show ip rns twamplight configuration all threshold',
  'show ip rns twamplight configuration all',
  'show ip rns twamplight configuration testsession num threshold',
  'show ip rns twamplight configuration testsession num',
  'show ip rns twamplight operationalstate all',
  'show ip rns twamplight operationalstate brief',
  'show ip rns twamplight operationalstate testsession num',
  'show ip rns twamplight statistics all testdelay',
  'show ip rns twamplight statistics all testloss',
  'show ip rns twamplight statistics testsession num testdelay',
  'show ip rns twamplight statistics testsession num testloss',
  'show ip rns twamplight statistics testsession num total',
  'show ip rns twamplightresponder configuration all',
  'show ip rns twamplightresponder configuration testsession num',
  'show ip rnsserver udpecho',
  'show ip route database',
  'show ip route ecmp',
  'show ip route fastreroute',
  'show ip route isis',
  'show ip route ospf',
  'show ip route static bfd',
  'show ip route static',
  'show ip route summary',
  'show ip route vrf name',
  'show ip route vrf word bgp',
  'show ip route vrf word count',
  'show ip route vrf word fastreroute',
  'show ip route vrf word summary bak0530',
  'show ip route vrf word summary',
  'show ip route vrf word',
  'show ip route weight',
  'show ip route',
  'show ip source binding dhcpsnooping',
  'show ip source binding stickymac',
  'show ip source binding',
  'show ip ssh',
  'show ip urpf interface dutport',
  'show ip urpf',
  'show ip verify sour',
  'show ip verify source',
  'show ip vrf count',
  'show ip vrf',
  'show ipsec manual sa word',
  'show ipsec proposal word',
  'show ipv6 address',
  'show ipv6 dhcp binding',
  'show ipv6 dhcp pool word',
  'show ipv6 dhcp pool',
  'show ipv6 dhcp relay destination all',
  'show ipv6 dhcp relay statistics',
  'show ipv6 dhcp relaydestination all',
  'show ipv6 dhcp server hide scc',
  'show ipv6 dhcp server statistics',
  'show ipv6 dhcp snooping binding mac',
  'show ipv6 dhcp snooping binding',
  'show ipv6 dhcp snooping packet',
  'show ipv6 dhcp',
  'show ipv6 fib route',
  'show ipv6 flow cache statistic dev num slot num',
  'show ipv6 interface brief',
  'show ipv6 interface dutport',
  'show ipv6 interface tunnel num',
  'show ipv6 interface vlan num rainfo',
  'show ipv6 interface vlan num',
  'show ipv6 local pool',
  'show ipv6 mld snooping gda',
  'show ipv6 nd snooping binding mac',
  'show ipv6 nd snooping binding',
  'show ipv6 nd snooping prefix',
  'show ipv6 nd snooping statistics',
  'show ipv6 nd',
  'show ipv6 neighbors detail overlayrouter num',
  'show ipv6 neighbors detail',
  'show ipv6 neighbors ipv6',
  'show ipv6 neighbors overlayrouter num',
  'show ipv6 neighbors statistics',
  'show ipv6 neighbors verbose',
  'show ipv6 neighbors vrf word',
  'show ipv6 neighbors',
  'show ipv6 ospf bgpls state',
  'show ipv6 ospf hide bgpls recordnlri num ip detail',
  'show ipv6 ospf hide bgpls recordnlri num ip',
  'show ipv6 ospf hide nsr',
  'show ipv6 ospf neighbo',
  'show ipv6 ospf neighbor',
  'show ipv6 ospf sync',
  'show ipv6 ospf word neighbor',
  'show ipv6 packet statistic total',
  'show ipv6 packet statistics total',
  'show ipv6 pathmtu vrf',
  'show ipv6 pathmtu',
  'show ipv6 pim sparsemode interface dutport detail',
  'show ipv6 pim sparsemode interface',
  'show ipv6 ref adjacency slot num',
  'show ipv6 ref adjacency statistics',
  'show ipv6 ref adjacency',
  'show ipv6 ref rout',
  'show ipv6 ref route detail device num slot num',
  'show ipv6 ref route detail device num',
  'show ipv6 ref route detail ipv6',
  'show ipv6 ref route fast',
  'show ipv6 ref route slot num',
  'show ipv6 ref route statistics slot num',
  'show ipv6 ref route statistics',
  'show ipv6 ref route vr word',
  'show ipv6 ref route vrf word',
  'show ipv6 ref route',
  'show ipv6 ref statistics',
  'show ipv6 route data',
  'show ipv6 route database',
  'show ipv6 route fastreroute',
  'show ipv6 route summary',
  'show ipv6 route vrf word fastreroute',
  'show ipv6 route vrf word summary',
  'show ipv6 route vrf word',
  'show ipv6 route',
  'show ipv6 source binding stickymac',
  'show ipv6 source binding',
  'show ipv6 tcp connect',
  'show ipv6 tcp statistics',
  'show ipv6 trafficfilter',
  'show ipv6 urpf',
  'show ipv6 vrrp br',
  'show ipv6 vrrp brief',
  'show ipv6 vrrp',
  'show isis counter',
  'show isis database detail',
  'show isis database verbose',
  'show isis gracefulrestart',
  'show isis interface',
  'show isis neighbor',
  'show isis neighbors detail',
  'show isis neighbors',
  'show isis route ipv6 verbose',
  'show isis segmentrouting adjacencysid',
  'show isis segmentrouting ilm',
  'show isis sync',
  'show isis topology',
  'show issu report',
  'show issu rollbacktimer',
  'show issu state detail',
  'show issu state',
  'show l2protocoltunnel gvrp',
  'show l2protocoltunnel stp',
  'show lacp counters',
  'show lacp summary',
  'show len',
  'show line console num',
  'show link state group',
  'show lldp localinformation interface dutport',
  'show lldp localinformation',
  'show lldp neighbors detail',
  'show lldp neighbors interface dutport',
  'show lldp neighbors order',
  'show lldp neighbors',
  'show lldp status interface dutport',
  'show lldp status',
  'show lldp tlvconfig interface dutport',
  'show lldp tlvconfig interface',
  'show loadbalance all',
  'show loadbalanceprofile default',
  'show loadbalanceprofile',
  'show logging config',
  'show logging mnemoniclist',
  'show logging',
  'show lsm capacity',
  'show lsm interface dutport',
  'show lsm interface',
  'show mac accessgroup',
  'show mac all',
  'show mac count',
  'show mac dynamic',
  'show mac flapping record',
  'show mac maxdynamicmaccount vlan num',
  'show mac other',
  'show mac share',
  'show mac vlan all',
  'show mac vlan num',
  'show mac vni num',
  'show mac',
  'show macaddress vsi num',
  'show macaddresstable address mac vni',
  'show macaddresstable agingtime',
  'show macaddresstable all',
  'show macaddresstable count interface dutport',
  'show macaddresstable count',
  'show macaddresstable dynamic interface dutport',
  'show macaddresstable maxdynamicmaccount interface dutport',
  'show macaddresstable maxdynamicmaccount vlan num',
  'show macaddresstable notification interface dutport',
  'show macaddresstable notification',
  'show macaddresstable share',
  'show macaddresstable vlan num',
  'show macaddresstable',
  'show macsec info interface dutport verbose',
  'show macsec statistics interface dutport',
  'show macvlan all',
  'show macvlan dynamic',
  'show macvlan interface',
  'show macvlan macaddress mac',
  'show macvlan static',
  'show macvlan vlan num',
  'show manuinfo',
  'show memory lowwatermark',
  'show memory',
  'show merge summary',
  'show mgmt virtual',
  'show mka session interface dutport verbose',
  'show mka statistics interface dutport',
  'show mls qos capacity',
  'show mls qos interface policers',
  'show mls qos maps cosdscp',
  'show mls qos maps dscpcos',
  'show mls qos maps dscpexp',
  'show mls qos maps expcos',
  'show mls qos maps expdscp',
  'show mls qos maps ipprecdscp',
  'show mls qos queueing',
  'show mls qos ratelimit interface dutport',
  'show mls qos ratelimit',
  'show mls qos scheduler',
  'show mls qos status',
  'show mmu bufferconfig interface dutport',
  'show mmu bufferconfig queuethreshold cell interface dutport',
  'show monitor session num',
  'show monitor',
  'show mpls forwardingtable fr',
  'show mpls forwardingtable frr',
  'show mpls forwardingtable ft',
  'show mpls forwardingtable ftn',
  'show mpls forwardingtable il',
  'show mpls forwardingtable ilm',
  'show mpls forwardingtable',
  'show mpls l2transport v',
  'show mpls l2transport vc count',
  'show mpls l2transport vc detail',
  'show mpls l2transport vc',
  'show mpls labelreach detail',
  'show mpls ldp backupfrr',
  'show mpls ldp bindings',
  'show mpls ldp frr',
  'show mpls ldp master',
  'show mpls ldp measure',
  'show mpls ldp neighbor all',
  'show mpls ldp neighbor vrf word',
  'show mpls ldp neighbor',
  'show mpls ldp nsr',
  'show mpls ldp parameters',
  'show mpls rib vrf word',
  'show mpls rib',
  'show mpls srgb',
  'show mpls srlb',
  'show mpls te segmentrouting tunnel num',
  'show ms mc',
  'show nacauthoruser',
  'show nak counters interface dutport',
  'show nak counters',
  'show net statistic',
  'show netconf authorization username word rulelist detail',
  'show netconf session bak0911',
  'show netconf session',
  'show nfpp arpguard hosts',
  'show nfpp arpguard summary',
  'show nfpp ipguard hosts statistics',
  'show nfpp tcpsynguard hosts',
  'show nfpp tcpsynguard summary',
  'show nfpp tcpsynguard trustedhost',
  'show nsm nhb byid num',
  'show ntp broadcastserver',
  'show ntp peer',
  'show ntp server',
  'show ntp status',
  'show outflowgroup num',
  'show outflowgroup summary',
  'show packet capture status',
  'show password policy',
  'show patch',
  'show pcep lsp num',
  'show pcep lsp',
  'show pcep peer ip statistics',
  'show pcep peer ip',
  'show pcep peer statistics',
  'show pcep peer',
  'show pcep',
  'show pgbuffer interface dutport',
  'show poe interfaces configuration',
  'show poe interfaces status',
  'show poe powersupply',
  'show policymap interface dutport',
  'show policymap statistics name word output',
  'show policymap',
  'show port maclink',
  'show portqueue statistics interface dutport',
  'show portqueue',
  'show portsecurity address',
  'show portsecurity binding',
  'show power fault',
  'show power temperature',
  'show power version',
  'show power',
  'show priorityflowcontrol deadlock statistics interface dutport',
  'show priorityflowcontrol statistics historytop interface dutport',
  'show priorityflowcontrol statistics interface dutport',
  'show priorityflowcontrol status interface dutport',
  'show priorityflowcontrol status',
  'show processes cpu',
  'show protocolvlan ipv4',
  'show protocolvlan profile',
  'show protocolvlan',
  'show proxyarp statistics',
  'show proxyarp',
  'show ps',
  'show qinq termination',
  'show qos bandwidth interface dutport',
  'show qos statistics interface dutport input',
  'show qos wredecn statistics interface dutport',
  'show queuebuffer interface dutport slot num',
  'show queuebuffer interface dutport',
  'show queuecounter interface dutport slot num',
  'show queuecounter interface dutport',
  'show queuecounter statistics interface dutport output',
  'show queueing wred interface dutport',
  'show radius dynamicauthorizationextension statistics',
  'show radius parameter',
  'show radius server',
  'show rdnd disable',
  'show rdnd pairs',
  'show rdnd problems',
  'show rdnd status',
  'show redirect',
  'show redundancy pairs',
  'show redundancy state',
  'show redundancy states',
  'show registrationtabl',
  'show registrationtable interfaces dutport',
  'show registrationtable',
  'show rldp interface dutport',
  'show rldp',
  'show role name word',
  'show routemap',
  'show route-res usage all',
  'show runningconfig interface dutport',
  'show runningconfig interface vlan num',
  'show savi ipv6 check source',
  'show savi ipv6 source binding',
  'show savi statistic',
  'show sbfd reflector discriminator',
  'show securityzone word word',
  'show segmentrouting policy counters',
  'show segmentrouting policy name word counters',
  'show segmentrouting policy name word',
  'show segmentrouting policy segmentlist counters',
  'show segmentrouting policy srv6',
  'show service',
  'show sflow',
  'show show rdnd pairs',
  'show smart manager detector all',
  'show smart manager history events',
  'show smart manager policy all',
  'show smart manager policy registered statistics',
  'show smart manager policy registered',
  'show snmp host',
  'show snmp traprecord',
  'show snmp user',
  'show snmp',
  'show snooping forward',
  'show snooping option82dot1x',
  'show sntp',
  'show spaninfo information globalinfo',
  'show spaninfo information outflowgroup',
  'show spanning tree counters',
  'show spanning tree summary',
  'show spanning tree',
  'show spanningtree mst configuration',
  'show spanningtree summary',
  'show spanningtree vstp information',
  'show split summary',
  'show sprs vxlantable',
  'show srp ref bsidmpls',
  'show srp ref bsidsrv6',
  'show srp ref nhp ipv6',
  'show srp ref sidlist',
  'show srv6 globalparameter',
  'show srv6 locator',
  'show srv6 policy bfd echo neighbor',
  'show srv6 policy policyname word',
  'show srv6 policy sbfd neighbor',
  'show srv6 policy statistics',
  'show srv6 policy',
  'show srv6 ref global',
  'show srv6 ref localsrv6id',
  'show srv6 sid counters',
  'show ssh',
  'show stats macall all',
  'show supervlan',
  'show switch id',
  'show switch virtual config',
  'show switch virtual dualactive aggregateport',
  'show switch virtual dualactive bfd',
  'show switch virtual link port',
  'show switch virtual link',
  'show switch virtual topology',
  'show switch virtual',
  'show switchmode status',
  'show tcp connect',
  'show tcp statistics bak',
  'show tcp statistics',
  'show temperature',
  'show tftpc time stat',
  'show track client',
  'show track num',
  'show track',
  'show traffic behavior word',
  'show traffic classifier word',
  'show traffic classifier',
  'show traffic policy word',
  'show traffic policy',
  'show trafficredirect interfaces dutport',
  'show trafficredirect',
  'show translationtable interfaces dutport',
  'show translationtable',
  'show tunnel information',
  'show upgrade autosync',
  'show upgrade autosync123',
  'show upgrade file flash word',
  'show upgrade history',
  'show upgrade startupversion',
  'show upgrade status',
  'show usergroup authentication more',
  'show usergroup authentication',
  'show usergroup mac mac',
  'show usergroup name word',
  'show usergroup summary',
  'show usergroup',
  'show users',
  'show vap consistencycheck global all',
  'show vap consistencycheck vap num all',
  'show vap consistencycheck vap num',
  'show vap summary',
  'show version detail',
  'show version devices',
  'show version module detail word',
  'show version slot',
  'show version slots',
  'show version',
  'show virtualac config',
  'show virtualac dualactive aggregateport',
  'show virtualac dualactive bfd',
  'show virtualac dualactive summary',
  'show virtualac link port',
  'show virtualac topology',
  'show virtualac',
  'show vlan id num',
  'show vlan privatevlan',
  'show vlan',
  'show voice vlan oui',
  'show voice vlan',
  'show vpdn log user word',
  'show vpdn log',
  'show vpdn session',
  'show vpdn tunnel pptp num',
  'show vrf detail word',
  'show vrf detail',
  'show vrf ipv6',
  'show vrf',
  'show vrrp br',
  'show vrrp brief',
  'show vrrp packet statistics',
  'show vrrp',
  'show vsd all',
  'show vsd detail',
  'show vxlan global',
  'show vxlan mac',
  'show vxlan mode',
  'show vxlan nd suppress',
  'show vxlan num bak',
  'show vxlan num',
  'show vxlan routeactive ipv6 vni num',
  'show vxlan routeactive ipv6',
  'show vxlan routebgp ipv6 vni num',
  'show vxlan server database',
  'show vxlan server route',
  'show vxlan server tunnel',
  'show vxlan statistics overlaytunnel num vni num',
  'show vxlan statistics overlaytunnel num',
  'show vxlan subport all',
  'show vxlan subport interface dutport',
  'show vxlan subport vni num',
  'show vxlan udpport',
  'show vxlan vnistatistics vni num',
  'show vxlan',
  'show web auth parameter',
  'show webauth capability',
  'show webauth control',
  'show webauth directarp',
  'show webauth directhost',
  'show webauth directsite',
  'show webauth guardipsegment',
  'show webauth portal',
  'show webauth portalcheck',
  'show webauth rdport',
  'show webauth template',
  'show webauth user all',
  'show webauth user ip ip',
  'show webauth user name word',
  'show webserver status',
  'show wlan arpcheck list',
  'show wlan hotbackup ip',
  'show wlan hotbackup',
  'show wred word',

]

export default allCliList;
